<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlazingStory.Addons" Version="1.0.0-preview.68" />
    <PackageReference Include="BlazingStory.ToolKit" Version="1.0.0-preview.68" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.5" />
  </ItemGroup>

</Project>
